from enum import Enum

class Color(Enum):
    blue = "blue"
    brown = "brown"
    default = "default"
    gray = "gray"
    green = "green"
    orange = "orange"
    pink = "pink"
    purple = "purple"
    red = "red"
    yellow = "yellow"

class RollupFunctionType(Enum):
    average = "average"
    checked = "checked"
    count_per_group = "count_per_group"
    count = "count"
    count_values = "count_values"
    date_range = "date_range"
    earliest_date = "earliest_date"
    empty = "empty"
    latest_date = "latest_date"
    max = "max"
    median = "median"
    min = "min"
    not_empty = "not_empty"
    percent_checked = "percent_checked"
    percent_empty = "percent_empty"
    percent_not_empty = "percent_not_empty"
    percent_per_group = "percent_per_group"
    percent_unchecked = "percent_unchecked"
    range = "range"
    unchecked = "unchecked"
    unique = "unique"
    show_original = "show_original"
    show_unique = "show_unique"
    sum = "sum"